name: jekyll build

on: 
  push:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.1
      - uses: actions/checkout@v3
      - name: jekyll build
        run: jekyll build --trace
      - name: trigger update
        run: curl -L ${{ secrets.UPDATE_URL }}
